# permissions for end users to view cloudbridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudbridge-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloud-bridge-crd
    app.kubernetes.io/part-of: cloud-bridge-crd
    app.kubernetes.io/managed-by: kustomize
  name: cloudbridge-viewer-role
rules:
- apiGroups:
  - ebme.lge.com
  resources:
  - cloudbridges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ebme.lge.com
  resources:
  - cloudbridges/status
  verbs:
  - get
